# Site settings
title: Nielsvanrongen.com
email: vanrongen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nielsvanrongen.com" # the base hostname & protocol for your site
twitter_username: nielsvanrongen
github_username:  redrohX
exclude: [original/]

# Build settings
markdown: kramdown

# Outputting
permalink:     /:title.html

# Sass
sass:
  style:  :compressed

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://nielsvanrongen.com'
  media: '/images/photos'
  ignore:
    - index.html
    - _config.yml
    - about.md
    - CNAME
    - feed.xml
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /fonts
    - /js
    - /original
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          placeholder: "2015-01-24 21:01:14"
      - name: "categories"
        field:
          element: "select"
          label: "category"
          options:
            - name: "Front-end"
              value: "front-end"
            - name: "Videogames"
              value: "videogames"
            - name: "Music"
              value: "music"
        - name: "tags"
          field:
            element: "text"
            label: "tags"
