# Site settings
title: Nielsvanrongen.com
email: vanrongen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nielsvanrongen.com" # the base hostname & protocol for your site
twitter_username: nielsvanrongen
github_username:  redrohX
exclude: [original/]

# Build settings
markdown: kramdown

# Outputting
permalink:     /:title.html

# Sass
sass:
  style:  :compressed

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://nielsvanrongen.com/'
  media: 'images/photos/'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2015-01-01 6:06:06"
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
